services:
  - docker

install:
  - docker-compose build test
  - docker-compose up test

script:
  - docker-compose run --rm test bundle exec rspec
  - docker-compose run --rm test bundle exec rubocop
  - docker-compose rm -f
