services:
  - docker

install:
  - docker-compose build test
  - docker-compose up test

script:
  - docker-compose run --rm test rspec
  - docker-compose run --rm test rubocop
  - docker-compose stop
  - docker-compose rm -f
