language:
  - ruby

rvm:
  - 2.6.2

env:
  - "RACK_ENV=travis_ci"

before_install:
  - cp config/database.travis.yml config/database.yml
  - gem update --system
  - gem install bundler
  - bundle install
  - rake db:migrate

services:
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

install:
  - bundle exec rspec
  - bundle exec rubocop
