<%= ENV['RACK_ENV'] %>:
  adapter: <%= ENV['DB_ADAPTER'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DATABASE'] %>
  port: <%= ENV['DB_PORT'] %>
  max_connections: <%= ENV['DB_MAX_CONNECTION'] %>
